### ISSUE TITLE
Show_map = false, still showing maps

### ISSUE THREAD

**Issue by gmahadwar** [HARPgroup/HARParchive#1168]
The show_map = false option isn't successfully turning off the map production. Currently, maps are still showing (ex. running https://github.com/HARPgroup/HARParchive/issues/1130#issuecomment-1932834017), and if there is an issue with the mapping then it quits due to an incomplete mapping value (if I can reproduce that error once I have enough internet to test full James I'll add that here). 

Addition 2/15/24 - the " Error: ! object 'mapfilename' not found " was the error I had seen previously

**Comment by glenncampagna** [comment]
### Findings 
- The map displayed when `show_map = FALSE` is not generated by that rmd run/render but rather pulled from the variable `mapfilename` already existing in the environment 
- When a render is done with `show_map = FALSE` with a completely empty environment, we get an error:
```
Quitting from lines 425-432 [View Map 1] (WSP_Regional_Summaries.Rmd)
Error:
! object 'mapfilename' not found
Backtrace:
 1. knitr::include_graphics(mapfilename)
 2. knitr:::native_encode(path)
 3. base::Encoding(x)
```
- I'd forgotten about this chunk in the WSP summary rmd:
```
#if (show_map == TRUE) {  
  knitr::include_graphics(mapfilename) #display map(s) PNG -- not functional inside loop
  if (mapMessage == TRUE) {
    message("The metric requested does not exist for this map.")
    message("Check your syntax/spelling. If correct, then this data has not been measured/modeled")
  }
#}
```
- Again we run into a problem with the knitr graphics display not working in a loop. We only want to display the map when the param is TRUE but can't control this method with an if loop

**Comment by glenncampagna** [comment]
### Resolved 
- This has been resolved, see PR https://github.com/HARPgroup/HARParchive/pull/1178
- The confusion for me was that the following _wont_ show a map:
```
if (show_map == TRUE) {
  knitr::include_graphics(mapfilename) #display map(s) PNG -- not functional inside loop
  if (mapMessage == TRUE) {
    message("The metric requested does not exist for this map.")
    message("Check your syntax/spelling. If correct, then this data has not been measured/modeled")
  }
}
```
but this _does_:
```
if (show_map == TRUE) {
  knitr::include_graphics(mapfilename) #display map(s) as PNG
}
```

**Comment by rburghol** [comment]
Hey @glenncampagna this is an interesting finding.  So, is your conclusion that simply including that message call breaks it?  I have a vague recollection of experiencing a similar thing where properly functioning code in the wrong render block broke my Rmd... but I have no specific examples to draw from right now undortunately.

Anyhow, I wonder if rather than the `message` command, which outputs to the console,  you used a `cat` command which would actually put the text into the final rendered document?
