### ISSUE TITLE
Fixing Smin Method Comparison 

### ISSUE THREAD

**Issue by glenncampagna** [HARPgroup/HARParchive#1200]
- See #1156 
- The comparison performed in https://github.com/HARPgroup/HARParchive/blob/master/HARP-2023-Summer/WaterAvailability/WaterAvailability_CaseStudies.Rmd that compares approximate and near-exact Smin methods is not functioning properly. 
- In Table 3 the `outside_pd` columns are supposed to quantify the # of days that separate the occurrences of the approximate and near-exact Smin values, if they are different 
  - This means that if the 2 values are the same (`SminL30mg_apx` and `SminL30mg_nex`), the `outside_pd_30` value should be 0
- This is currently not the case for the comparison, and needs to be fixed 
- We also want to add +/- to the `outside_pd` columns
  - Would need to document the meaning of +/- once this is implemented 

**Example:**
![image](https://github.com/HARPgroup/HARParchive/assets/104520197/c81ca443-108e-4782-a9bf-98bf176e5bbb)

**Comment by glenncampagna** [comment]
### Retrieving object class for Sugar Hollow @rburghol 

 ```
pid <- 4712896 #Sugar Hollow pid 

  token = ds$get_token(rest_pw) #needed for elid function
  elid <- om_get_model_elementid(
    base_url = site,
    mid = pid
  )
  rm(token)

  dat <- fn_get_runfile(elid, runid_dem, site= omsite,  cached = FALSE) #get timeseries data (read in as zoo)
  mode(dat) <- 'numeric'
  
  #Get model to get object class
  model <- RomProperty$new(ds,list( 
    featureid = 68308,  #Sugar Hollow featureid
    propcode = 'vahydro-1.0'
  ),TRUE)
  
  #Get object class 
  object_class <- RomProperty$new(ds,list( #get vahydro-1.0 model feature from vahydro
    featureid = model$pid,
    propname = 'object_class'
  ),TRUE)  
  
  object_class <- object_class$propcode
 
  object_class

```

**Comment by rburghol** [comment]
```
model <- RomProperty$new(ds,list( 
   featureid = 68308,  #Sugar Hollow featureid
   propcode = 'vahydro-1.0'
 ),TRUE)
obj_url <- paste(json_obj_url, model$pid, sep="/")
#Get model info using ds$auth_read to authenticate and grab model info+data
model_info <- ds$auth_read(imp_obj_url,  "text/json", "")
model_info <- fromJSON(imp_model_info)
elid <- model_info[[1]]$om_element_connection$value
object_class <- model_info[[1]]$object_class$value

```

**Comment by glenncampagna** [comment]
### Errors when implementing the above 

```
model_info <- ds$auth_read(obj_url,  "text/json", "")
model_info <- fromJSON(model_info)

Error: Argument 'txt' must be a JSON string, URL or file.

class(model_info)

[1] "list"
```
