### ISSUE TITLE
Intermix maps and tables in rmd

### ISSUE THREAD

**Issue by EllaF21** [HARPgroup/HARParchive#1222]
**Update for 4/10 Meeting**

- Per @rburghol suggestion, I am looking at using the index values for the tables and maps to get them to coordinate.
- So far uncesseful as it seems `knitr::include_graphics` for the maps is possibly temperamental in multiple loops. 
- It often just removes the maps entirely but will keep the tables. The `rivmapfilename` used to `ggsave` our maps might also be causing the issue. 
- Current code is as follows, and is also in my branch ella0409 at lines 764 to 780. 
- Any insight welcomed, possible other ideas, to compare just the run_label from the config, titles as a whole between the two, or create new indexing. 

Thanks :) 
```
for (k in 1:length(run_config$riverseg_metrics)){
  #map
  if (show_map == TRUE) {
    knitr::include_graphics(rivmapfilename)
  }
    #table
    if (tablemessage2==TRUE) {
      message("A column in the table is completely NA values, 
          likely meaning the metric requested is not modeled for this data
          or the segments are all tidal")
    }
    cat(knitr::knit_print(get(paste0('table', k))))
    cat("\n\n\\pagebreak\n")
  }
```
Current render for markdown 
```
rmarkdown::render(paste0(github_location, "/HARParchive/HARP-2023-Summer/Mapping/WSP_Regional_Summaries.Rmd"),
   output_file = paste0(export_path,"/JL6_7430_7320test"),
   output_format = "word_document",
   params = list(
      origin = "JL6_7430_7320",
      origin_type = "basin",
      featr_type = "facility",
      featrs_file = paste0(export_path, "/JL6_7430_7320_featrs_sf.csv"),
      featrs_file_map_bubble_column = "wsp2020_2040_mgy",
      featrs_file_table_column = c("runid_11_wd_mgd","runid_13_wd_mgd","five_yr_avg","wsp2020_2040_mgy"),
      rsegs_file = paste0(export_path, "/JL6_7430_7320_rsegs_sf.csv"),
      run_set = "wsp_2020_2040",
      runid_list = c("runid_11", "runid_13", "runid_17" ,"runid_19"),
      crs_default = 4326,
      map_style = "custom",
      bbox_type = "auto",
      show_map = TRUE)
)
```

**Comment by COBrogan** [comment]
Hi @EllaF21. I'm having trouble fetching ```ella0409```, but the problem of the current set-up is likely related to #1183 and my comment [here](https://github.com/HARPgroup/HARParchive/issues/1183#issuecomment-1959728927). As you suspected, ```include_graphics()``` works best in top-level expressions. The "value" of include_graphics() basically need to be returned from whatever loop or statement it is in, which may not be possible with the _if_ statement within the _for_ loop. Would you mind pushing your branch again? I'll try to take a look at this prior to the meeting this afternoon and see if we can develop an alternative strategy for these pesky knit commands.

**Comment by EllaF21** [comment]
Hi @COBrogan, I just put it up as a pull request so that should let you see it now. I wont be at the meeting this afternoon, but if you find any alternative strategy possibility please let me know!

**Comment by rburghol** [comment]
```
rmarkdown::render(paste0(github_location, "/HARParchive/HARP-2023-Summer/Mapping/WSP_Regional_Summaries.Rmd"),
   output_file = paste0(export_path,"/JL6_7430_7320test"),
   output_format = "word_document",
   params = list(
      origin = "JL6_7430_7320",
      origin_type = "basin",
      featr_type = "facility",
      featrs_file = paste0(export_path, "/JL6_7430_7320_featrs_sf.csv"),
      featrs_file_map_bubble_column = "wsp2020_2040_mgy",
      featrs_file_table_column = c("runid_11_wd_mgd","runid_13_wd_mgd","five_yr_avg","wsp2020_2040_mgy"),
      rsegs_file = paste0(export_path, "/JL6_7430_7320_rsegs_sf.csv"),
      run_set = "wsp_2020_2040",
      runid_list = c("runid_11", "runid_13", "runid_17" ,"runid_19"),
      crs_default = 4326,
      map_style = "custom",
      bbox_type = "auto",
      show_map = TRUE)
)
```
