### ISSUE TITLE
Lake Chesdin Water Availability Case Study Extra Upstream Basins 

### ISSUE THREAD

**Issue by glenncampagna** [HARPgroup/HARParchive#1236]
- Part of #1156 
- Lake Chesdin's riverseg ID: `JA5_7480_0001`
- When mapping Water Availability Case Study watersheds I see a couple extra riversegs:
![image](https://github.com/HARPgroup/HARParchive/assets/104520197/13e5a0d9-390d-4380-8cce-0a12b6dbd604)
- This is not caused by `fn_extract_basin`, shown by:
```
fn_extract_basin(rsegs, "JA5_7480_0001")

riverseg blankColumn
121 JA2_7410_7470          NA
258 JA4_7470_7480          NA
263 JA4_7340_7470          NA
281 JA1_7640_7280          NA
402 JA4_7280_7340          NA
581 JA1_7600_7570          NA
592 JA2_7570_7480          NA
604 JA2_7550_7280          NA
639 JA5_7480_0001          NA
693 JA1_7641_7640          NA
```
so it must be caused elsewhere

**Comment by rburghol** [comment]
Thanks, @glenncampagna  can you can you give us the data frame, , or at least a handful of rows with the column names, that does have the bad data in it?  You probably have to drop the geometry :-)

**Comment by glenncampagna** [comment]
### Dataframe used for Lake Chesdin Map with bad/extra data
  ```
pid                             propname                     hydrocode featureid      riverseg wd_cumulative_mgd ps_cumulative_mgd l30_Qout_dem l90_Qout_dem
357 4706210                      Appomatox River vahydrosw_wshed_JA4_7470_7480     67969 JA4_7470_7480        1.69950564       1.167055326    14.912029    50.767023
356 4711440  West Creek (Deep Creek, Appomattox) vahydrosw_wshed_JA2_7570_7480     68323 JA2_7570_7480        0.32468381       0.004258646     1.386668     9.393615
355 4706275                      Appomatox River vahydrosw_wshed_JA4_7340_7470     67974 JA4_7340_7470        1.63588198       1.167055326    13.432933    42.916172
354 4711570   Appomatox River above Farmville VA vahydrosw_wshed_JA2_7550_7280     68336 JA2_7550_7280        1.31438192       0.000000000     4.699557    18.760683
353 4711168 West Creek (Deep Creek, Appommattox) vahydrosw_wshed_JA1_7600_7570     68310 JA1_7600_7570        0.32468381       0.000000000     1.079929     7.411552
352 4708361                      Appomatox River vahydrosw_wshed_JA4_7280_7340     68119 JA4_7280_7340        1.63588198       0.969609638    12.998865    42.048828
350 4706483                           Bush River vahydrosw_wshed_JA1_7640_7280     67992 JA1_7640_7280        0.06125804       0.000000000     2.538971     8.256033
349 4704572                           Flat Creek vahydrosw_wshed_JA2_7410_7470     67825 JA2_7410_7470        0.00000000       0.000000000     0.969305     6.167827
358 4713947              George F. Brasfield Dam vahydrosw_wshed_JA5_7480_0001     68373 JA5_7480_0001       35.78890594       1.171314050    18.408332    54.052786
155 4712371                        Jackson River vahydrosw_wshed_JU4_7330_7000     67980 JU4_7330_7000       45.03272205      40.935091545   146.108900   167.910793
156 4710541                          James River vahydrosw_wshed_JU4_7000_7300     68243 JU4_7000_7300       48.85346480      43.266934771   167.840637   206.620656
```

**Comment by rburghol** [comment]
Looking thru the code, I think there are a number of places where you could (really, should) be using `fn_extract_basin`, but instead are matching a list (that you obtained from `fn_extract_basin`). The reason we stress use of `fn_extract_basin` is that it is a uniform meyhod, even if it's bad for some reason we can make systematic mistakss.

So this:
```
ups_data <- metric_data[metric_data$riverseg %in% ups_segs$riverseg,]

```
Should be this:
```
ups_data <- fn_extract_basin(metric_data, ds_seg_carv)

```

Unkess there is a reason *not* to use `fn_extract_basin` of course. It works on **any** dataframe with a riverseg.  I don't know if this causes your error, but it should be replaced either way.  Then there'll be one less method to debug and more readable code.

**Comment by glenncampagna** [comment]
Thanks for digging into this @rburghol . I'm unsure if `fn_extract_basin()` will return all upstream basins if we use `metric_data` as the riversegs dataframe because it does not contain all possible segment IDs. This is what @COBrogan  found here https://github.com/HARPgroup/HARParchive/issues/1213#issuecomment-2026139960 (with a smaller dataframe with more missing segments, but I would think the logic is the same). This is why `fn_extract_basin()` is always used with `rsegs` which is a comprehensive list of river segments so that none are missed, and then the metrics for each of those segments is retrieved from `metric_data` using the resulting list of upstream segments. Maybe an alternative could be to join `rsegs` and `metric_data` so that `metric_data` contains all possible segment IDs? Let me know your thoughts

**Comment by rburghol** [comment]
@glenncampagna -- yes, and I agree with your fix, there should be a full join performed with metric_data on the left and rsegs on the right (I think, check that out).  Then once performed, all should work inside `fn_extract_basin`

**Comment by glenncampagna** [comment]
- This problem has been resolved, and was caused by downstream river segments not being removed between loop iterations, so the downstream segments from the previous case study (Moomaw) were being added to the Chesdin dataframe by mistake.
Added `rm(list = ls(pattern = 'ds_seg'))`
<img width="1499" alt="image" src="https://github.com/HARPgroup/HARParchive/assets/104520197/5ad623cd-4373-4c66-ab07-fabd95e1d9ac">
