### ISSUE TITLE
Introduce sample data sets and gages

### ISSUE THREAD

**Issue by rburghol** [HARPgroup/HARParchive#1270]
### USGS 01634000 Strasburg VA
- Daymet: http://deq1.bse.vt.edu:81/files/met/usgs_ws_01634000-daymet-2022-2023.csv
- PRISM: http://deq1.bse.vt.edu:81/files/met/usgs_ws_01634000-prism-2022-2023.csv
- NLDAS: tbd
- Rscript to match precip and USGS: https://github.com/HARPgroup/HARParchive/blob/master/HARP-2024-2025/access-file.R
   - This script does various summaries of daily precip and flow, change in flow, change in next day flow
   - Has variations for weekly flow, and analyzing a single month.
   - Introduces `sqldf` for data frame summaries
   - Uses dataRetrieval module
   - Introduces use of `lm` for simple linear regression, and plotting of model regressions.
   - Question 1: "why do certain days repeat non-zero values?" 
      - see 2022/03/22 and 2022/03/23 data for repeating daymet and prism values
      - http://deq1.bse.vt.edu:81/met/daymet/2022/081/ORIGINAL_daymet_precip2022-03-22.bil_CBP.gtiff
      - http://deq1.bse.vt.edu:81/met/PRISM/2022/082/PRISM_ppt_stable_4kmD2_20220323_bil.bil_CBP.gtiff
      - http://deq1.bse.vt.edu:81/met/daymet/2022/081/ORIGINAL_daymet_precip2022-03-22.bil_CBP.gtiff
      - http://deq1.bse.vt.edu:81/met/daymet/2022/082/ORIGINAL_daymet_precip2022-03-23.bil_CBP.gtiff
   - Question 2: "can we do a weekly precip versus **change** in flow?"
   - Question 3: "how about weekly change in flow versus previous week precip?"

**Comment by COBrogan** [comment]
The storm separation code we developed in 2018 is [here](https://github.com/HARPgroup/HARParchive/tree/cd4c0380b65e61a6c0f0fea42dfa48cff369d99c/HARP-2018-2019/Flow%20Stats). Glancing through it, I believe it may be a good first step to working through this. I think the logic here is sound, but it needs some more recent testing. I'm going to try spinning it up early next week and will report back. For now, I'm going to pull baseflow separation from ```grwrat```, a [package ](https://tsamsonov.github.io/grwat/articles/baseflow.html) that I like the looks of as it has storm separation functions in the package itself (although they seem complicated). Doesn't have to be our final answer on this, but it gives me a starting point.

**Comment by durelles** [comment]
[like]  Scott, Durelle reacted to your message:
________________________________

**Comment by rburghol** [comment]
R Code to look at changes in Q, on days when Q is increasing over prior day (evidence of rain increase).
```
# do all months and assemble a barplot of R^2
ndd_stats <- data.frame(row.names=c('month', 'rsquared_a'))
for (i in 1:12) {
  mod_prism_mon_nz_ndd <- lm(nextday_d_cfs ~ prism_p_cfs, data=comp_data[which((comp_data$mo == i) & (comp_data$nextday_d_cfs > 0)),])
  dsum <- summary(mod_prism_mon_nz_ndd)
  plot(mod_prism_mon_nz_ndd$model$nextday_d_cfs ~ mod_prism_mon_nz_ndd$model$prism_p_cfs)
  ndd_stats <- rbind(ndd_stats, data.frame(i, dsum$adj.r.squared))
}
barplot(ndd_stats$dsum.adj.r.squared ~ ndd_stats$i)
```

![image](https://github.com/HARPgroup/HARParchive/assets/4571170/038dccce-16ae-4471-acf0-74de47a4d9e5)

**Comment by mwdunlap2004** [comment]
I also created a look at last weeks precipitation compared to this weeks streamflow, a similar overall graph, but in certain parts of the year it seems to have a much stronger correlation
`last_week_data <- sqldf(
  "select min(week_begin) as week_begin, yr, wk, mo, min(dataset_day_begin) as dataset_day_begin,
     Lag(daymet_p_in,1) OVER(ORDER BY dataset_day_begin) as lastweek_daymet_p_in, 
     Lag(daymet_p_cfs,1) OVER(ORDER BY dataset_day_begin) as lastweek_daymet_p_cfs,
     Lag(prism_p_in,1) OVER(ORDER BY dataset_day_begin) as lastweek_prism_p_in, 
     Lag(prism_p_cfs,1) OVER(ORDER BY dataset_day_begin) as lastweek_prism_p_cfs,
     usgs_cfs as usgs_cfs, today_d_cfs as today_d_cfs, 
     nextday_d_cfs as nextday_d_cfs
   from week_data
   group by yr, wk
   order by yr, wk
  "
)

last_week_data = last_week_data[-1,]


las_week_ndd_stats <- data.frame(row.names=c('month', 'rsquared_a'))
for (i in 1:12) {
  las_week_prism_mon_nz_ndd <- lm(usgs_cfs ~ lastweek_prism_p_cfs, data=last_week_data[which((last_week_data$mo == i) & (last_week_data$usgs_cfs > 0)),])
  las_week_dsum <- summary(las_week_prism_mon_nz_ndd)
  plot(las_week_prism_mon_nz_ndd$model$usgs_cfs ~ las_week_prism_mon_nz_ndd$model$lastweek_prism_p_cfs)
  las_week_ndd_stats <- rbind(las_week_ndd_stats, data.frame(i, las_week_dsum$adj.r.squared))
}
barplot(las_week_ndd_stats$las_week_dsum.adj.r.squared ~ las_week_ndd_stats$i)
summary(las_week_prism_mon_nz_ndd)`

![3c428660-f4d7-4583-b9b8-ed6ebd25e10e](https://github.com/HARPgroup/HARParchive/assets/156853523/4faeb133-428d-4b19-aec5-5364f00e08f0)
