### ISSUE TITLE
plotting residuals easily

### ISSUE THREAD

**Issue by rburghol** [HARPgroup/HARParchive#1326]
@ilonah22 @COBrogan @mwdunlap2004 I found out that we can create a normal plot output from an `lm` by including an argument indicating the number of the plot that we want to save:
```
jun_model <- data_lm$atts$lms[[6]]
plot(jun_model, 1)

```

**Comment by mwdunlap2004** [comment]
Using what Connor recomended for the JSON, I was able to edit our residual plot function with this plotting method.
<img width="302" alt="Screenshot 2024-07-29 at 8 55 06 AM" src="https://github.com/user-attachments/assets/494ef4f9-5527-4bc2-ace9-17ac04c67392">
![daymet_01665500_residual6](https://github.com/user-attachments/assets/ac98e54d-6085-47a0-b687-9aa22e5f1e9e)
This is the same residual we had looked at last Thursday that was different when taken directly from data_lm, and when from the JSON we had made, with this method the residual plot looks correct both ways
