### ISSUE TITLE
Writing to .h5 file in hsp2 using python

### ISSUE THREAD

**Issue by gcambridge** [HARPgroup/HARParchive#245]
***Note on Jupyter Notebooks:*** Documentation in the hsp2 repo is available as pdf or as the output of a Juypter Notebook, which does not require running the Jupyter notebook.

### Overview of Tasks
- [x] What are the function arguments that the hsp2 `to_hdf` functions take?
- [x] What are the function arguments for the underlying methods that `to_hdf()` calls?
- [x] Can these be used to determine index setting etc?
- [x] Is there some earlier routine that creates some sort of *hdf data source* that has index settings?

### Writing to .h5 files
Per [this documentation](https://github.com/respec/HSPsquared/wiki/HSP2_Design_Details), hsp2 uses the python data analysis package `pandas` to read and write to h5 files. This allows for the use of pandas series and dataframes, which are simpler than the HDF5 datasets. 

The pandas method `.to_hdf(output.h5, dataframe)` is used to write data frames to h5 files, where `output.h5` is the intended .h5 output file, and `dataframe` is the pandas dataframe to write.

Write_ts() information removed, see the **Misinterpretation of the write_ts() function** comment

**Comment by nicoledarling** [comment]
### Functions of `to_hdf` command
In the hsp2, it uses the path, key, data_columns, and format functions.
![image](https://user-images.githubusercontent.com/104520315/177386653-266ffe1b-a6b0-4441-ac1d-49f3f8ea4e44.png)

Path (`self._store`): this indicates the HDF store

Key (`'RUN_INFO/VERSIONS'`): identifies the group in the store

Data_columns: list of columns to create as indexed data columns for on-disk queries, TRUE means all columns

Format: 't' means table format, it is written in PyTables structure, other option is 'f' which means fixed format

The` hsp2_log` and `versioning `before the command indicate the data frames being used

### Other functions for` to_hdf `

Mode: mode to open a file, three options for this

- ‘W’ means write, a new file is created

- ‘A’ means append, existing file is opened

- ‘R+’ is similar to ‘a’ but file needs to already exist

Append: append the input data to the existing

Complevel: indicates the compression level for the data, value of 0 would disable compression

Complib: specifies the compression library that is used 

Errors: specifies how encoding and decoding errors are to be handled

Dropna: if true, na rows will not be written to store

**Comment by gcambridge** [comment]
### Misinterpretation of the `write_ts()` function
It seems like hsp2 may use `to_hdf()` directly, with no intermediate functions. See this [link](https://github.com/respec/HSPsquared/wiki/HSP2_Design_Details#:~:text=In%20HSP2%2C%20an%20entire%20DataFrame%20or%20Series%20is%20read%20in%20one%20Pandas%20read%20operation%20and%20the%20entire%20DataFrame%20or%20Series%20is%20written%20(replacing%20any%20existing%20dataset)%20in%20one%20operation.%20HDF5%20does%20allow%20for%20finer%20control%20of%20reading%20and%20writing%2C%20but%20HSP2%20does%20not%20currently%20use%20that%20capability.). The function `write_ts()` seems to create a timeseries, assign it to a panda dataset object, and then write it to an h5 (using `to_hdf`).

**Comment by rburghol** [comment]
Thanks @nicoledarling this looks like the right path!  These are in a `_read_table()` function, and we would expect to see a `_write_table()` function of some sort, but, nevertheless, the fact that the *pandas* lib has the time resolution (units) as an argument to its timestamp creator, and that hsp2 uses nano seconds tells us much.

So... it's on purpose.  We *could* ask why, but at this point I would file this away under *things to ask someone someday*, since knowing that it is intentional suffices for my own personal curiosity at the moment -- in other words, if it intentional, then we can assume that all other routines expect this nanoseconds, and thus we can be somewhat confident that we aren't going to be surprised by a switcheroo at some time in the future.
