### ISSUE TITLE
HARP Week of 2022/08/15

### ISSUE THREAD

**Issue by rburghol** [HARPgroup/HARParchive#499]
- [x] Review last week #400 
- [x] discuss schedule to wrap up before a week or so off. 
- [x] Docs: [Uniqueness bullets to the wiki for permanent reference](https://github.com/HARPgroup/vahydro/wiki/Uniqueness-in-VAHydro-Data-Model-and-REST)
- [x] Run export/Analysis
  - [x] Testing running on Rockfish
  - [x] Testing running on Meherrin
  - [x] Testing running on Occoquan
  - [x] Integrate analysis scrpts (i.e. metric calculation and REST) in run_river.csh
  - [x] Verify flows in Rockfish #443, Meherrin #463 and Occoquan #498
    - [x] How do the flow values compare to p532sova_2021?  
    - [x] Can we conclude that the process developed to route flow from one h5 segment to the next is *actually* working like the standard HSPF technique in the CBP model?  Let's have some visualizations and numerical analyses to validate this... 
- [x] FTABLE work #331 
- [x] hsp2 work

**Comment by glenncampagna** [comment]
- [ ] Create script which exports hydr csv using hspf ROVOL csv files `[seg]_0111.csv`, including columns for index, ROVOL, and Qout

Julia has a first version of this script finished but we are waiting to push and test because of some wifi problems she's having
